export { default as TwitterIcon } from "./TwitterIcon"
export { default as FacebookIcon } from "./FacebookIcon"
export { default as InstagramIcon } from "./InstagramIcon"
export { default as ChevronDoubleRightIcon } from "./ChevronDoubleRightIcon"
export { default as ChatIcon } from "./ChatIcon"
